### ISSUE TITLE
does not build in arm environment (qemu, raspbian jessie, ubuntu mate 16.04)

### ISSUE THREAD

**Issue by fanoush** [puppeh/vc4-toolchain#1]
It builds fine in x64 jessie, it can compile https://github.com/christinaa/rpi-open-firmware and the result works on the pi, excellent!

However it does not build in
1. raspbian chroot under qemu userspace emulation as per https://wiki.debian.org/RaspberryPi/qemu-user-static
2. real latest raspbian on pi3 (gcc version same as in x64 jessie !?)
3. ubuntu mate 16.04 on pi3 - newer gcc (5.4?)

the error is still the same, it fails building libgcc - there is error in configure stage

configure:3693: error: in `/opt/vc4-toolchain/gcc-build/vc4-elf/libgcc':
configure:3696: error: cannot compute suffix of object files: cannot compile
See`config.log' for more details.

I am attaching full build.log (see the end for the error) and also the gcc-build/vc4-elf/libgcc/config.log

Would be nice to have it working directly on the pi3 so I could quickly hack the open source firmware just with Pi3 and Zero.
[vc4-toolchain-builderrors.zip](https://github.com/puppeh/vc4-toolchain/files/446512/vc4-toolchain-builderrors.zip)

**Comment by itszor** [comment]
I've managed to reproduce this in a raspbian chroot environment, but so far I have no clue what's causing it. That environment's kind of slow & awkward to debug in, but maybe we can figure it out eventually...

Thanks!

**Comment by fanoush** [comment]
Thanks for reproducing. I guess that the freshly build compiler does not compile small test program and crashes with internal compiler error. What is strange is that it seems to fail on memory allocation/mmap and the error is permission denied ??

configure:3653: checking for suffix of object files
configure:3675: /opt/vc4-toolchain/gcc-build/./gcc/xgcc -B/opt/vc4-toolchain/gcc-build/./gcc/ -B/opt/vc4-toolchain/prefix/vc4-elf/bin/ -B/opt/vc4-toolchain/prefix/vc4-elf/lib/ -isystem /opt/vc4-toolchain/prefix/vc4-elf/include -isystem /opt/vc4-toolchain/prefix/vc4-elf/sys-include    -c -g -O2  conftest.c >&5
conftest.c: In function 'main':
conftest.c:16:1: internal compiler error: in add_allocno_hard_regs, at ira-color.c:272
 }
 ^
mmap: Permission denied
Please submit a full bug report,
with preprocessed source if appropriate.
See http://gcc.gnu.org/bugs.html for instructions.

I would perhaps understand qemu-user but in native raspbian/ubuntu when building as root why would mmap give permissin denied? maybe some flags passed to it that do not work on ARM? And BTW building on PI3 was faster than qemu-user on  2.4 GHz Intel Xeon® E5-2673 v3 (Haswell)

**Comment by fanoush** [comment]
Just a followup but I guess you already figured all that out already. The program that fails looks like this

`/* confdefs.h */
#define PACKAGE_NAME "GNU C Runtime Library"
#define PACKAGE_TARNAME "libgcc"
#define PACKAGE_VERSION "1.0"
#define PACKAGE_STRING "GNU C Runtime Library 1.0"
#define PACKAGE_BUGREPORT ""
#define PACKAGE_URL "http://www.gnu.org/software/libgcc/"
/* end confdefs.h.  */
int
main ()
{
  ;
  return 0;
}`
and indeed it fails when building it by hand from command line
`/opt/vc4-toolchain/gcc-build/./gcc/xgcc -B/opt/vc4-toolchain/gcc-build/./gcc/ -B/opt/vc4-toolchain/prefix/vc4-elf/bin/ -B/opt/vc4-toolchain/prefix/vc4-elf/lib/ -isystem /opt/vc4-toolchain/prefix/vc4-elf/include -isystem /opt/vc4-toolchain/prefix/vc4-elf/sys-include -c -g -O conftest.c
conftest.c: In function 'main':
conftest.c:14:1: internal compiler error: in add_allocno_hard_regs, at ira-color.c:272
 }
 ^
mmap: Permission denied
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
`
It also fails with -Os or -O but it does not fail and compiles without error when removing -O completely.

And the place where it fails -  ira-color.c:272 is the line with
  gcc_assert (! hard_reg_set_empty_p (set));
so it looks like this method gets empty set of registers which is unexpected? but  I still don't understand why it fails on mmap - the hard_reg_set_empty_p macro just compares it to some value so maybe it comes from the gcc_assert method itself?

**Comment by itszor** [comment]
The two possibilities I can think of are (a) there's a bug in the host ARM toolchain used to compile the compiler, or (b) there's some genuine ARM-specific bug (maybe signedness of char, or something?) that's causing an issue, somehow. (Or maybe something as trivial as out-of-memory, if mmap is failing, but I wouldn't expect the same behaviour under qemu and hardware then.)

**Comment by fanoush** [comment]
I had an idea that it could be 32 vs 64 bit issue, 32bit is not much used on intel nowadays. yesterday I set up fedora24 64bit on the pi3 (from https://www.kraxel.org/blog/2016/06/new-raspberry-pi-images-uploaded/ ) and got gcc build deps installed today morning (took ages), will check today evening how it builds there

**Comment by msperl** [comment]
I have seen this also - compiling on a RPI3.
I have tried all compiler variants - gcc 4.7, 4.8, 4.9, 6.2.
It compiles fine on x86_64 and works.

My guess is that it is related to 32/64 bit somewhere, but then compiling a avr-crosscompiler from the same sources works fine, so it could be in the patches themselves that somewhere rely implicitly on 64 bit width...

**Comment by fanoush** [comment]
Actually I tested it on fedora arm 64bit and it compiled fine this part mentioned in this issue but it fails later at building stage2 compiler. And there it is some normal syntax error, maybe fedora24 gcc is too new for compiling this older gcc source. I will post exact error. I wanted to hack the source and fix the error but so far didn't get to it.

To confirm the 64bit issue one could verify it by trying to build it in 32bit intel version of same ubuntu or debian distro. It should fail there with same error if it is related to 64 bit values.

**Comment by msperl** [comment]
Note that I have built out a VM with Centos 6.8 using i386:

```
[root@localhost vc4-toolchain]# gcc -v
Using built-in specs.
Target: i686-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch=i686 --build=i686-redhat-linux
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC)
[root@localhost vc4-toolchain]# uname -a
Linux localhost 2.6.32-642.6.1.el6.i686 #1 SMP Tue Oct 4 22:41:38 UTC 2016 i686 i686 i386 GNU/Linux
```

And that one compiles fine:

```
[root@localhost vc4-toolchain]# /build/vc4-toolchain/prefix/bin/vc4-elf-gcc -v
Using built-in specs.
COLLECT_GCC=/build/vc4-toolchain/prefix/bin/vc4-elf-gcc
COLLECT_LTO_WRAPPER=/build/vc4-toolchain/prefix/libexec/gcc/vc4-elf/6.0.0/lto-wrapper
Target: vc4-elf
Configured with: ../gcc-vc4/configure --target=vc4-elf --prefix=/build/vc4-toolchain/prefix --disable-nls --disable-ssp --enable-languages=c --disable-decimal-float --disable-threads --disable-libatomic --disable-libitm --disable-libsanitizer --disable-libquadmath --disable-lto --enable-sjlj-exceptions
Thread model: single
gcc version 6.0.0 20150922 (experimental) (GCC)
```

So if it is something to do with integer sizes/signedness... then it has to do with some other "minor" differences between the architectures (it is not 32 bit on its own that triggers this)...

Maybe we should try getting the patches up to the latest patches of gcc (6.2) and see if the issue goes away then? 
Or maybe cgen is not 100% clean for arm?...

**Comment by msperl** [comment]
So a few more compile-tests using different platforms:
- jessie-arm-rpi3: fails (xgcc: add_allocno_hard_regs) - gcc 4.7.3, 4.8.3, 4.9.2, 6.2.0
- centos7-x86_64-kvm: compiles - gcc 4.8.5
- centos6-i386-kvm: compiles - gcc 4.4.7
- wheezy-arm-beagleboneblack: fails (xgcc: add_allocno_hard_regs) - gcc 4.7.2
- centos7-aarch64-rpi3: compiles stage 1 - gcc 4.8.5

Compiling on jessie-arm-rpi3 with `CFLAGS="-g -O0 -fsigned-char" CXXFLAGS="$CFLAGS" ./build-all.sh` (similar to what is set for the i386/x86_64 gcc) also produces the same add_allocno_hard_regs result.

**Comment by msperl** [comment]
OK - so I have added some "minimal" logging to add_allocno_hard_regs (logging parameters):

```
diff --git a/gcc/ira-color.c b/gcc/ira-color.c
index 8433479..cc0213a 100644
--- a/gcc/ira-color.c
+++ b/gcc/ira-color.c
@@ -256,6 +256,7 @@ add_allocno_hard_regs (HARD_REG_SET set, int64_t cost)
   struct allocno_hard_regs temp;
   allocno_hard_regs_t hv;

+fprintf(stderr,"HERE %lx %llu\n", set, cost);
   gcc_assert (! hard_reg_set_empty_p (set));
   COPY_HARD_REG_SET (temp.set, set);
   if ((hv = find_hard_regs (&temp)) != NULL)
```

and compiled xgcc on arm and on x86_64.

Then I compiled a "minimal" c program (`int main() { return 0; }`)
on ARM:

```
root@rasp3a:/build/vc4-toolchain/gcc-build#  /build/vc4-toolchain/gcc-build/./gcc/xgcc -B/build/vc4-toolchain/gcc-build/./gcc/ -B/opt/vc4/vc4-elf/bin/ -B/opt/vc4/vc4-elf/lib/ -isystem /opt/vc4/vc4-elf/include -isystem /opt/vc4/vc4-elf/sys-include    -c -g -O2 test.c
HERE 1 0
HERE 2 0
HERE 4 0
HERE 8 0
HERE 10 0
HERE 20 0
HERE 40 0
HERE 80 0
HERE 100 0
HERE 200 0
HERE 400 0
HERE 800 0
HERE 1000 0
HERE 2000 0
HERE 4000 0
HERE 8000 0
HERE 10000 0
HERE 20000 0
HERE 40000 0
HERE 80000 0
HERE 100000 0
HERE 200000 0
HERE 400000 0
HERE 800000 0
HERE 4000000 0
HERE 0 0
test.c: In function 'main':
test.c:1:1: internal compiler error: in add_allocno_hard_regs, at ira-color.c:260
 int main() {return 0;}
```

On x86_64:

```
[root@build gcc-build]# /build/vc4-toolchain/gcc-build/./gcc/xgcc -B/build/vc4-toolchain/gcc-build/./gcc/ -B/opt/vc4/vc4-elf/bin/ -B/opt/vc4/vc4-elf/lib/ -isystem /opt/vc4/vc4-elf/include -isystem /opt/vc4/vc4-elf/sys-include    -c -g -O2 test.c
HERE 1 0
HERE 2 0
HERE 4 0
HERE 8 0
HERE 10 0
HERE 20 0
HERE 40 0
HERE 80 0
HERE 100 0
HERE 200 0
HERE 400 0
HERE 800 0
HERE 1000 0
HERE 2000 0
HERE 4000 0
HERE 8000 0
HERE 10000 0
HERE 20000 0
HERE 40000 0
HERE 80000 0
HERE 100000 0
HERE 200000 0
HERE 400000 0
HERE 800000 0
HERE 4000000 0
HERE fffffff804ffffff 0
HERE 4ffffff 0
```

The difference starts with "fffffff804ffffff", which looks like the mask of all the registers that are "usable" masking r24(GP), r25(SP), r27, r28, r29, r30)

So - as far as I can tell - it is compiler arithmetic (calculating 0xfffffff804fffff) that does not "work" properly on arm - possibly the wrong data type is used during static evaluation or in a method.

Maybe someone has an idea where that comes from...

**Comment by msperl** [comment]
as a sidenote - rebasing the vc4-patchset on the upstream "gcc-6-branch" branch works with 2 changes:
- `5b5b62e cfns: fix mismatch in gnu_inline attributes` does not apply - this must go somewhere else as there has been a reorg
- a change is needed to implement the api change done by the gcc core:

```
diff --git a/gcc/config/vc4/vc4.c b/gcc/config/vc4/vc4.c
index 9bee5d5..8acb2da 100644
--- a/gcc/config/vc4/vc4.c
+++ b/gcc/config/vc4/vc4.c
@@ -210,7 +210,9 @@ vc4_target_address_cost (rtx address ATTRIBUTE_UNUSED,
 }

 static void
-vc4_print_operand_address (FILE *stream, rtx x)
+vc4_print_operand_address (FILE *stream,
+                          machine_mode mode ATTRIBUTE_UNUSED,
+                          rtx x)
 {
   switch (GET_CODE (x))
     {
@@ -331,7 +333,7 @@ vc4_print_operand (FILE *stream, rtx x, int code)
             asm_fprintf (stream, "%r", REGNO (x));
             break;
           case MEM:
-            vc4_print_operand_address (stream, XEXP (x, 0));
+            vc4_print_operand_address (stream, VOIDmode, XEXP (x, 0));
             break;
           default:
             output_addr_const (stream, x);
```

**Comment by fanoush** [comment]
> as far as I can tell - it is compiler arithmetic (calculating 0xfffffff804fffff) that does not "work" properly 

thanks, great idea for logging it, so looks like it uses signed long arithmetic with -1 instead of unsigned 8000000 somewhere? maybe building with something like -funsigned-long would fix it but it appears there is no such gcc flag (unlike -funsigned-char)
EDIT: oh, there is -unsigned-long

**Comment by msperl** [comment]
To me it looks as if HARD_REG_SET is handled "strangely" on arm, but I am not getting to any conclusion where it really goes wrong...

The only thing that surprises me is that it works fine on i386, which should also be using the same bit-length for unsigned int, but this one did not show it.

**Comment by msperl** [comment]
looking at it some more - the function after preprocessing looks like this:

```
# 41 "../../gcc-vc4/gcc/hard-reg-set.h"
typedef unsigned long HARD_REG_ELT_TYPE;
...
static allocno_hard_regs_t
add_allocno_hard_regs (HARD_REG_ELT_TYPE set, int64_t cost)
{
  struct allocno_hard_regs temp;
  allocno_hard_regs_t hv;
...
```

And that is identical for arm and for x86_64.

there is a provision in gcc/hard-reg-set.h:

```
#if FIRST_PSEUDO_REGISTER <= HOST_BITS_PER_WIDEST_FAST_INT

#define HARD_REG_SET HARD_REG_ELT_TYPE

#else
...
```

This always evaluates to true, as FIRST_PSEUDO_REGISTER is not a define but a enum, so cpp can not expanded/process it and surprisingly assumes "true" as the resulting computation.

I wonder what it looks like on i386 - unfortunately I do not have a machine available any longer...

I am testing this right now with the following:

```
diff --git a/gcc/config/vc4/vc4.h b/gcc/config/vc4/vc4.h
index 2d8ad09..e7dd921 100644
--- a/gcc/config/vc4/vc4.h
+++ b/gcc/config/vc4/vc4.h
@@ -154,9 +154,10 @@ enum {
     PC_REG = 31, /* The PC is not exposed, but this is useful in pop insns.  */
     AP_REG = 32, /* 32 */
     FP_REG, /* 33 */
-    CC_REG, /* 34 */
+    CC_REG /* 34 */
+
+#define FIRST_PSEUDO_REGISTER 35

-    FIRST_PSEUDO_REGISTER
 };

 /* Specify the registers used for certain standard purposes.
```

**Comment by msperl** [comment]
Initial tests show that the "current" compile issue is fixed - I am running a full compile right now.
Created https://github.com/puppeh/gcc-vc4/pull/1 to fix that issue.

**Comment by fanoush** [comment]
btw, just verified how easy is to overflow into negative number without any warning (even with -Wall), this code:

```
#include <stdio.h>

int main(int argc,char *argv[]){
    long l=0x40000000;
    long long ll=0;
    ll=l+l+0x40000000LL;
    fprintf(stderr,"%llx\n", ll);
    return 0;
}

```

produces 0xc0000000 on 64bit and ffffffffc00000000 on 32bit arm. Even compilation with -unsingned-long does not help. only redefining l as unsigned long produces correct result (or adding l+l after the LL constant).

**Comment by msperl** [comment]
So the full compile ran without any issues on my rpi3 with the patch mentioned above applied.
The 32-bit build-system-issue has been solved as far as I am concerned.
Building all helloworld examples is working.

**Comment by msperl** [comment]
As a sidenote: https://github.com/msperl/gcc-vc4/tree/gcc-6-branch-vc4 contains a version rebased on the gcc-6.2-branch.
Only patch https://github.com/puppeh/gcc-vc4/commit/5b5b62e84d886ed9ad3d8f5a8c474234d74279e8 is not compatible with 6.2 and had to be left out. Also https://github.com/msperl/gcc-vc4/commit/0fa78ad7ed5437367c586016887c1ca3a543862b was needed to add an additional argument to vc4_print_operand_address.

**Comment by itszor** [comment]
Oh! Another instance of http://panic.cs-bristol.org.uk/wp/?p=56 then? Very nice bug hunting, thank you!

**Comment by fanoush** [comment]
I can confirm it builds fine on PI3 and the result builds rpi-open-firmware just fine too and runs on my Zero. Many thanks :-)

**Comment by fanoush** [comment]
Since the fix is commited here https://github.com/puppeh/gcc-vc4/commit/ac03f169afda78ee4c06e95da5bb76d99d9c8362 I am closing this. Thanks again :-)
