### ISSUE TITLE
Build error "ISO C++ forbids comparison between pointer and integer"

### ISSUE THREAD

**Issue by a-v-s** [puppeh/vc4-toolchain#10]
Build does not complete, with error "ISO C++ forbids comparison between pointer and integer" in ../../gcc-vc4/gcc/ubsan.c.  I am using gcc version 7.1.1 on Arch Linux.
I have attached a build log. 

[build.log.txt](https://github.com/puppeh/vc4-toolchain/files/1100206/build.log.txt)

**Comment by itszor** [comment]
I think you get this with recent host GCC versions. It's fixed upstream. I'll take a look when I get the chance...

**Comment by itszor** [comment]
This is fixed now. Sorry for the delay!
