### ISSUE TITLE
Toolchain doesn't compile when following install instructions (Ubuntu 16.04)

### ISSUE THREAD

**Issue by Ten0** [puppeh/vc4-toolchain#14]
The building process seems to generate invalid files and then try to build upon them.
Specifically, `binutils-build/binutils/./syslex.c` only contains : 
```
main() { return 0; }
```
and this triggers a "main redefinition error".
But there are also some missing defines...
```
../../binutils-vc4/ld/ldlang.c:212:24: error: ‘SPECIAL’ undeclared (first use in this function)
   if (s->constraint != SPECIAL)
```
etc...

This happens with or without CGEN.

Here is the full build log (CGEN off) : 
https://pastebin.com/3z8jtai4

Thanks in advance

**Comment by itszor** [comment]
Could you try installing flex and bison and retrying the build?

**Comment by furkantokac** [comment]
I had the same issue on KDE Neon (based on Ubuntu 16.04). After "flex" and "bison", it worked flawlessly. All I need was;
```BASH
apt install flex
apt install bison
```
 Maybe this issue can be mentioned on README file.

Thanks for the support and a great toolchain!

**Comment by itszor** [comment]
I've updated the README file. Thank you for the report and the kind words!
