### ISSUE TITLE
[Feature Request] Vector Assembly Support

### ISSUE THREAD

**Issue by zoudeying** [puppeh/vc4-toolchain#2]
I had tried out this repo and find it quite useful to program the Scaler Core in the VPU.
For my application, I would like to inquire about feature for the Vector Core.

When will the Vector Assembly feature be enabled? Any plan now? Assembly should be enough for me.

Thanks.

**Comment by itszor** [comment]
If you check out the head of vc4 branch of the binutils-vc4 repository, then you will find many of the vector instructions have been implemented already, though the work is not yet complete (particularly with regard to assembly, vs. disassembly). I am planning to work on finishing it some time soonish.

**Comment by itszor** [comment]
Vector assembly and disassembly is supported, though most likely still has bugs. Please open individual issues for those as/when you find them.

Thanks!
