### ISSUE TITLE
Compile Error on openSUSE

### ISSUE THREAD

**Issue by NF3RN0** [puppeh/vc4-toolchain#3]
Not sure if it is my version of Guile or what is causing it. Maybe someone out there knows? I've tried to install guile-1.8 but to no avail. I might try to compile it under a virtual box with Debian if all else fails.

I am attaching my build log at the bottom.

`libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../../binutils-vc4/opcodes -I. -I../../binutils-vc4/opcodes -I../bfd -I../../binutils-vc4/opcodes/../include -I../../binutils-vc4/opcodes/../bfd -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -g -O2 -MT dis-init.lo -MD -MP -MF .deps/dis-init.Tpo -c ../../binutils-vc4/opcodes/dis-init.c -o dis-init.o
make[5]: Entering directory '/home/dustin/Development/vc4-toolchain/binutils-build/opcodes'
/bin/sh ../../binutils-vc4/opcodes/cgen.sh opcodes ../../binutils-vc4/opcodes "`if test -f ../guile/libguile/guile ; then echo ../guile/libguile/guile; else echo guile ; fi`-l ../../binutils-vc4/opcodes/../cgen/guile.scm -s" \
  ../../binutils-vc4/opcodes/../cgen "-v" vc4 vc4 ../../binutils-vc4/opcodes/../cpu/vc4.cpu ../../binutils-vc4/opcodes/../cpu/vc4.opc \
  "" ""
mv -f .deps/dis-init.Tpo .deps/dis-init.Plo
/bin/sh ./libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../../binutils-vc4/opcodes  -I. -I../../binutils-vc4/opcodes -I../bfd -I../../binutils-vc4/opcodes/../include -I../../binutils-vc4/opcodes/../bfd    -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -g -O2 -MT cgen-opc.lo -MD -MP -MF .deps/cgen-opc.Tpo -c -o cgen-opc.lo ../../binutils-vc4/opcodes/cgen-opc.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../../binutils-vc4/opcodes -I. -I../../binutils-vc4/opcodes -I../bfd -I../../binutils-vc4/opcodes/../include -I../../binutils-vc4/opcodes/../bfd -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -g -O2 -MT cgen-opc.lo -MD -MP -MF .deps/cgen-opc.Tpo -c ../../binutils-vc4/opcodes/cgen-opc.c -o cgen-opc.o
;;; note: auto-compilation is enabled, set GUILE_AUTO_COMPILE=0
;;;       or pass the --no-auto-compile argument to disable.
;;; compiling /home/dustin/Development/vc4-toolchain/binutils-build/opcodes/../../binutils-vc4/opcodes/../cgen/guile.scm
;;; WARNING: compilation of /home/dustin/Development/vc4-toolchain/binutils-build/opcodes/../../binutils-vc4/opcodes/../cgen/guile.scm failed:
;;; ERROR: Syntax error:
;;; /home/dustin/Development/vc4-toolchain/binutils-build/opcodes/../../binutils-vc4/opcodes/../cgen/guile.scm:13:4: definition in expression context, where definitions are not allowed, in form (define (eval1 expr) (eval expr (current-module)))
ice-9/psyntax.scm:1274:12: In procedure #<procedure deb050 (test then else)>:
ice-9/psyntax.scm:1274:12: Syntax error:
/home/dustin/Development/vc4-toolchain/binutils-build/opcodes/../../binutils-vc4/opcodes/../cgen/guile.scm:13:4: definition in expression context, where definitions are not allowed, in form (define (eval1 expr) (eval expr (current-module)))
make[5]: *** [Makefile:1295: run-cgen] Error 1
make[5]: Leaving directory '/home/dustin/Development/vc4-toolchain/binutils-build/opcodes'
make[4]: *** [Makefile:1392: stamp-vc4] Error 2
make[4]: *** Waiting for unfinished jobs....
mv -f .deps/cgen-opc.Tpo .deps/cgen-opc.Plo
make[4]: Leaving directory '/home/dustin/Development/vc4-toolchain/binutils-build/opcodes'
make[3]: *** [Makefile:1009: all-recursive] Error 1
make[3]: Leaving directory '/home/dustin/Development/vc4-toolchain/binutils-build/opcodes'
make[2]: *** [Makefile:666: all] Error 2
make[2]: Leaving directory '/home/dustin/Development/vc4-toolchain/binutils-build/opcodes'
make[1]: *** [Makefile:3003: all-opcodes] Error 2
make[1]: Leaving directory '/home/dustin/Development/vc4-toolchain/binutils-build'
make: *** [Makefile:826: all] Error 2
`

Cheers!
[build.zip](https://github.com/puppeh/vc4-toolchain/files/470775/build.zip)

**Comment by itszor** [comment]
Hi! If you're not intending to modify the CGEN source files, you can probably get away without having guile installed at all. Can you try changing the WITHCGEN setting in the build-all.sh script?

**Comment by fanoush** [comment]
Had same error yesterday with fedora 24, looks like default 'guile' command runs guile 2.0 not 1.8, after temprorarily renaming guile in /usr/bin to guile-2.0 and linking guile-1.8 to guile (ln -s guile-1.8 guile) it worked.
