### ISSUE TITLE
Compile Fail Ubuntu

### ISSUE THREAD

**Issue by microhobby** [puppeh/vc4-toolchain#4]
I try to compile with Ubuntu. Could you help me with this error.

Follow Build.log:
[build.txt](https://github.com/puppeh/vc4-toolchain/files/479292/build.txt)

**Comment by fanoush** [comment]
/home/matheus/rpi3/bootloader/vc4-toolchain/binutils-vc4/missing makeinfo --split-size=5000000 --split-size=5000000 --no-split -I../../binutils-vc4/etc -o standards.info ../../binutils-vc4/etc/standards.texi
WARNING: `makeinfo' is missing on your system.  You should only need it if
         you modified a`.texi' or `.texinfo' file, or any other file
         indirectly affecting the aspect of the manual.  The spurious
         call might also be the consequence of using a buggy`make' (AIX,
         DU, IRIX).  You might want to install the `Texinfo' package or
         the`GNU make' package.  Grab either from any GNU archive site.
Makefile:161: recipe for target 'standards.info' failed
make[3]: **\* [standards.info] Error 1

so you are missing makeinfo comand, did you install gcc build dependencies as explained in README.md? makeinfo/Texinfo is one of them

**Comment by microhobby** [comment]
For some reason the build-dep doesn't resolve all dependencies for GCC in my distro (UBUNTU 16LTS).
For resolve dependencies I run: 

`sudo apt-get install libmpfr-dev libgmp3-dev libmpc-dev flex bison`

After this compile with success. Thank you for your attention.
