### ISSUE TITLE
What do I do about lots of scalar32 errors in check.sh?

### ISSUE THREAD

**Issue by kjcole** [puppeh/vc4-toolchain#6]
[check.zip](https://github.com/puppeh/vc4-toolchain/files/557441/check.zip)
Tonight, I started from scratch again. I deleted the repo, did the recursive clone again, ran the build-all.sh (after commenting out the WITHCGEN), and finally the check.sh. I don't know enough to know what to look for in the 10992-line check.log, but the tail end of it lists:

```
# of expected passes            51826
# of unexpected failures        10752
# of unexpected successes       6
# of expected failures          98
# of unsupported tests          1564

```

Suggestions?  Thanks! (I've zipped and attached check.log)

**Comment by kjcole** [comment]
[gcc.zip](https://github.com/puppeh/vc4-toolchain/files/557484/gcc.zip)
Not that I know what to do about it, but I think it's the scalar32 error that's killing stuff. 
In the testresults-2016-10-27-1/gcc.log,

`egrep "(Error|scalar32)" gcc.log`

turned up 10728 lines. Removing the filenames and line numbers and then asking it for the uniq lines gives me:

```
Error: operand out of range (400020000 not between -67108864 and 67108863)
Error: symbol `_func' is already defined
Error: unrecognized form of instruction `trap 1'
Exception: scalar32: Unsupported instruction.
```

10709 of the lines were the scalar32 error.

**Comment by itszor** [comment]
Ah, I know what's going on here -- recent experimentation to get stuff working on hardware has meant that we're now using an instruction very early on in the execution of every program that the simulator doesn't support. I'll fix this some time soon. Apologies!

**Comment by kjcole** [comment]
So, the answer to my question is "Wait".  That's something I'm skilled at and know how to do. ;-)  I'm just glad to know it wasn't something I was doing wrong at my end. Thanks.

**Comment by itszor** [comment]
You could try again now, but simulator tests will appear to degrade quite heavily because (uh) non-zero exit codes weren't being propagated out properly from the simulator.

**Comment by itszor** [comment]
(The "scalar32" bug should be fixed though)

**Comment by kjcole** [comment]
Down from 10728 errors to 429 errors. Yay!
