### ISSUE TITLE
Unable to save all registers on stack 

### ISSUE THREAD

**Issue by ghost** [puppeh/vc4-toolchain#9]
Not sure if this is seen as a bug or not.  I can understand the logic behind the way it is so I really  dont know if this should be closed without changes or not.

I wanted to do the following instruction (16 bit instruction 029f)
stm r0-r31, (--sp)

I am unable to directly do this.  I can .ascii "\x9f\x02" but that is far less elegant.  It appears the system registers do not have an alias allowing for this instruction to be assembled.

**Comment by itszor** [comment]
Try:
stm r0-pc,(--sp)

The aliases are:
r24: gp
r25: sp
r26: lr
r27: r27
r28: r28
r29: r29
r30: sr
r31: pc

HTH!

**Comment by ghost** [comment]
that never occurred to me and it probably should have. I could only think of aliases in one direction.

That does work.  Thanks.
